
#阿里云地址
spring:
  datasource:
    url: jdbc:postgresql://47.95.204.81:5432/monitor_db
    username: wuao
    password: wuao1992
    dbcp2:
      driver-class-name: org.postgresql.Driver


#部署机地址

#spring:
#  datasource:
#    url: jdbc:postgresql://127.0.0.1:5432/monitor_db
#    username: postgres
#    password: postgres
#    dbcp2:
#      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 172800
logging:
  level:
    root: info
#server:
#  servlet:
#    context-path: /SRPM

